site_name: Julia Notes
site_author: Samuele Carcagno
theme: readthedocs
#theme_dir: mkdocs_bootstrap
repo_url: https://github.com/sam81/julia-notes

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

docs_dir: 'build'

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - admonition
  
pages:
    - Introduction: 'index.md'
    - Simple intro: 'simple_intro.md'
    - Data Types: 'datatypes.md'
    - Mutable and immutable objects: 'mutable_immutable.md'
    - Installing packages: 'installing_packages.md'
    - Creating packages: 'creating_packages.md'
    - DataFrames: 'dataframes.md'
    - Random Numbers and Sampling: 'random.md'
    - Parallel Processing: 'parallel_processing.md'
    - Graphics - PlotlyJS: 'plotlyJS.md'
    - Graphics - Gadfly: 'gadfly.md'
    - Graphics - VegaLite: 'vegalite.md'
    - Graphics - PyPlot: 'pyplot.md'
    - Graphics - ggplot2: 'ggplot2.md'
    - Workflow: 'workflow.md'
    - Sound: 'sound.md'
