site_name: Julia Notes
site_author: Samuele Carcagno
theme: readthedocs
repo_url: https://github.com/sam81/julia-notes

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

docs_dir: 'build'

markdown_extensions:
  - extra
  - tables
  - fenced_code
  
pages:
    - Introduction: 'index.md'
    - Data Types: 'datatypes.md'
    - DataFrames: 'dataframes.md'
    - Random Numbers and Sampling: 'random.md'
    - Parallel Processing: 'parallel_processing.md'
    - Graphics - Gadfly: 'gadfly.md'
    - Graphics - VegaLite: 'vegalite.md'
    - Graphics - PyPlot: 'pyplot.md'
    - Graphics - ggplot2: 'ggplot2.md'
    - Workflow: 'workflow.md'
